name: glossarium
description: "Eine App zur Sammlung von Fachbegriffen."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cloud_firestore: ^4.14.0
  file_picker: ^6.1.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_ui_auth: ^1.12.1
  firebase_ui_oauth_google: ^1.2.17
  flutter_redux: ^0.10.0
  google_sign_in: ^6.2.1
  open_filex: ^4.3.4
  path: ^1.8.3
  path_provider: ^2.1.2
  pdf: ^3.10.7
  redux: ^5.0.0
  share_plus: ^7.2.1
  sqflite: ^2.3.2

dev_dependencies:
  flutter_lints: ^3.0.1
  icons_launcher: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/

