name: glossarium
description: "Eine App zur Sammlung von Fachbegriffen."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cloud_firestore: ^5.0.2
  file_picker: ^8.0.6
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_ui_auth: ^1.12.1
  firebase_ui_oauth_google: ^1.2.17
  flutter_redux: ^0.10.0
  google_sign_in: ^6.2.1
  open_filex: ^4.3.4
  path: ^1.8.3
  path_provider: ^2.1.2
  pdf: ^3.10.7
  redux: ^5.0.0
  share_plus: ^9.0.0
  sqflite: ^2.3.2
  intl: any

dev_dependencies:
  flutter_lints: ^4.0.0
  icons_launcher: ^2.1.7

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/